### ISSUE TITLE
We need to add event materials.

### ISSUE THREAD

**Issue by chadsansing** [chadsansing/iot-escape-room-workshop#4]
These include the agenda, the activities descriptions, the master slides, printables (design deck, maps, connected device cards), etc..

**Comment by chadsansing** [comment]
Added:

- Design canvas.
- Design deck.
- Master slides.

**Comment by chadsansing** [comment]
Added:

- day-1 activities.
- examples.

**Comment by chadsansing** [comment]
Added:

- day-1 methods
- day-2 methods
- images

Waiting for city map and *privacy not included cards.

**Comment by chadsansing** [comment]
Added:

- city map
- connected device cards

@KatieMitch, do you want to add the poster and stickers?

**Comment by KatieMitch** [comment]
[Poster_IoTEscapeRoom_GREEN.pdf](https://github.com/chadsansing/iot-escape-room-workshop/files/1819919/Poster_IoTEscapeRoom_GREEN.pdf)
[Poster_IoTEscapeRoom_BLUE.pdf](https://github.com/chadsansing/iot-escape-room-workshop/files/1819920/Poster_IoTEscapeRoom_BLUE.pdf)
[StickerSheet_CHA_IoTFox.pdf](https://github.com/chadsansing/iot-escape-room-workshop/files/1819921/StickerSheet_CHA_IoTFox.pdf)

@chadsansing Did this work??

**Comment by KatieMitch** [comment]
NOTE: We need to update the colors on the canvas to match the design deck.

**Comment by chadsansing** [comment]
Those are great, @KatieMitch - thanks! If you have the raw design files, we could share those, too, for folks to edit. I will ping Martin re: canvas.

**Comment by chadsansing** [comment]
Added stickers & posters. Pinged Martin.

cc @mskell

**Comment by chadsansing** [comment]
Updated canvas .pdf and canvas and deck .indd files added. 

Closing.
